PLEX_SERVER_URL: "http://192.168.1.5:32400"

HOTWORD: jarvis # Valid options: alexa, americano, blueberry, bumblebee, computer, grapefruit, grasshopper, hey barista, hey google, hey siri, jarvis, ok google, pico clock, picovoice, porcupine, smart mirror, snowboy, terminator, view glass
