[tool.pytest.ini_options]
filterwarnings = [
    "ignore:ssl.SSLContext\\(\\) without protocol argument is deprecated.:DeprecationWarning",
    "ignore:ssl.PROTOCOL_TLS is deprecated:DeprecationWarning"
]